version: '2'
services:
  test_mariadb:
    restart: always
    container_name: test_mariadb
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - test_mariadb:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_PASSWORD=1RNMfMt9gpKZrP2QGaOicb8QYoGbmbS9wE05SDTzzOY=
      - MARIADB_DATABASE=bitnami_wordpress
    networks:
      test_internal:
        aliases:
          - mariadb
  test_wordpress:
    container_name: test_wordpress
    restart: always
    image: wordpress-nginx:latest
    build: .
    volumes:
      - test_wordpress:/bitnami/wordpress
      - ./nginx/server-block.conf:/opt/bitnami/nginx/conf/server_blocks/_server-block.conf
      # - ./nginx/application-block-normal.conf:/opt/bitnami/nginx/conf/bitnami/_app.conf
      - ./nginx/application-block-basic-auth.conf:/opt/bitnami/nginx/conf/bitnami/_app.conf
      - .htpasswd:/opt/bitnami/.htpasswd
    depends_on:
      - test_mariadb
    environment:
      PHP_MEMORY_LIMIT: 512m
      PHP_MAX_EXECUTION_TIME: 3600
      PHP_POST_MAX_SIZE: 1G
      PHP_UPLOAD_MAX_FILESIZE: 1G
      # WORDPRESS_DATABASE_HOST: test_mariadb
      # WORDPRESS_DATABASE_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_USER: bn_wordpress
      WORDPRESS_DATABASE_PASSWORD: 1RNMfMt9gpKZrP2QGaOicb8QYoGbmbS9wE05SDTzzOY=
      WORDPRESS_DATABASE_NAME: bitnami_wordpress
    networks:
      - shared
      - test_internal
  test_ftp:
    container_name: test_ftp
    depends_on:
      - test_wordpress
    restart: always
    image: delfer/alpine-ftp-server:latest
    volumes:
      - test_wordpress:/bitnami/wordpress/wp-content
    environment:
      USERS: "bob|67te2KTJELKZqtKZ|/bitnami/wordpress/wp-content|1001"
      MIN_PORT: 3021
      MAX_PORT: 3031
    expose:
      - 3021-3031
    ports:
      - 2021:21
      - 3021-3031:3021-3031
  phpmyadmin:
    restart: always
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOSTS: test_mariadb
      # PMA_ARBITRARY: 1
      # PMA_PORT: 3306
      # PMA_USER: bn_wordpress
      # PMA_PASSWORD: 1RNMfMt9gpKZrP2QGaOicb8QYoGbmbS9wE05SDTzzOY=
      # PMA_CONTROLUSER: 
      # PMA_CONTROLUSER_PASSWORD: 
      # APACHE_PORT: 27019
    depends_on:
      - test_mariadb
    ports:
      - 27019:80
    networks:
      - shared
      - test_internal

  proxy:
    container_name: proxy_server
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    networks:
      - shared
    depends_on:
      - test_wordpress
volumes:
  test_mariadb:
    name: test_mariadb
    external: true
  test_wordpress:
    name: test_wordpress
    external: true
networks:
  shared:
    name: shared
    external: true
  test_internal:

