#!/bin/bash

source $(pwd)/config

echo "...generate .htpasswd"
htpasswd -bn $HT_PASSWD_USER $HT_PASSWD_PASSWORD > $(pwd)/.htpasswd

HT_PASSWD_BASE64=$(echo -n "$HT_PASSWD_USER:$HT_PASSWD_PASSWORD" | openssl base64)

echo "...prepare basic auth configuration file"
sed "s/{HT_PASSWD_BASE64}/$HT_PASSWD_BASE64/g" $(pwd)/nginx/application-block-basic-auth.conf.template > $(pwd)/nginx/application-block-basic-auth.conf
