#!/bin/bash

source $(pwd)/config

echo "...prepare site.conf"
site_conf_header="events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    client_max_body_size 128M;

    # access_log /var/log/nginx/access.log main;
    sendfile on;
    #tcp_nopush on;
    keepalive_timeout 120;
    gzip on;
    gzip_comp_level 2;
    gzip_http_version 1.0;
    gzip_proxied any;
    gzip_min_length 1100;
    gzip_buffers 16 8k;
    gzip_types text/css text/x-component application/x-javascript application/javascript text/javascript text/x-js text/richtext text/plain text/xsd text/xsl text/xml image/bmp application/java application/msword application/vnd.ms-fontobject application/x-msdownload image/x-icon application/json application/vnd.ms-access video/webm application/vnd.ms-project application/x-font-otf application/vnd.ms-opentype application/vnd.oasis.opendocument.database application/vnd.oasis.opendocument.chart application/vnd.oasis.opendocument.formula application/vnd.oasis.opendocument.graphics application/vnd.oasis.opendocument.spreadsheet application/vnd.oasis.opendocument.text audio/ogg application/pdf application/vnd.ms-powerpoint image/svg+xml application/x-shockwave-flash image/tiff application/x-font-ttf audio/wav application/vnd.ms-write application/font-woff application/font-woff2 application/vnd.ms-excel;
    gzip_disable \"MSIE [1-6].(?!.*SV1)\";
    gzip_vary on;

    server {
        listen 8080;
        server_name ${SITE_NAMES}_php;
        client_max_body_size 128M;
        root /var/www/html/;

        location / {
            etag on;
            if_modified_since exact;
            add_header Pragma \"public\";
            add_header Cache-Control \"max-age=3600, public\";
            add_header Referrer-Policy \"no-referrer-when-downgrade\";
            try_files \$uri \$uri/ /index.php?\$args;
            #try_files \$uri \$uri/ /index.php\$is_args\$args;
            index index.html index.htm index.php;
        }

        location ~ ^/wp-json/ {
            # if permalinks not enabled
            rewrite ^/wp-json/(.*?)$ /?rest_route=/\$1 last;
        }

        location ~ \.(css|htc|less|js|js2|js3|js4)$ {
            expires 31536000s;
            etag on;
            if_modified_since exact;
            add_header Pragma \"public\";
            add_header Cache-Control \"public\";
            add_header Referrer-Policy \"no-referrer-when-downgrade\";
            try_files \$uri \$uri/ /index.php?\$args;
        }

        location ~ \.(asf|asx|wax|wmv|wmx|avi|avif|avifs|bmp|class|divx|doc|docx|exe|gif|gz|gzip|ico|jpg|jpeg|jpe|webp|json|mdb|mid|midi|mov|qt|mp3|m4a|mp4|m4v|mpeg|mpg|mpe|webm|mpp|_otf|odb|odc|odf|odg|odp|ods|odt|ogg|ogv|pdf|png|pot|pps|ppt|pptx|ra|ram|svg|svgz|swf|tar|tif|tiff|_ttf|wav|wma|wri|xla|xls|xlsx|xlt|xlw|zip)$ {
            expires 31536000s;
            etag on;
            if_modified_since exact;
            add_header Pragma \"public\";
            add_header Cache-Control \"public\";
            add_header Referrer-Policy \"no-referrer-when-downgrade\";
            try_files \$uri \$uri/ /index.php?\$args;
        }

        location ~ \.php$ {
            try_files \$uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_buffers 8 16k;
            fastcgi_buffer_size 32k;
            fastcgi_connect_timeout 300;
            fastcgi_send_timeout 300;
            fastcgi_read_timeout 300;
            fastcgi_pass ${SITE_NAMES}_php:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
            fastcgi_param PATH_INFO \$fastcgi_path_info;
            # Hide PHP headers
            fastcgi_hide_header X-Powered-By;
            fastcgi_hide_header X-CF-Powered-By;
        }

        location @extensionless-php {
            rewrite ^(.*)$ \$1.php last;
        }

        add_header Referrer-Policy \"no-referrer-when-downgrade\";
    }
"

site_conf_footer="
}"

site_conf="${site_conf_header}${site_conf_footer}"

echo "$site_conf" >$(pwd)/nginx/${SITE_NAMES}.conf
