#!/bin/bash

echo "...load configuration"
source $(pwd)/config

echo "...create shared network"
docker network create --attachable shared || true

echo "...create volume"
for i in "${!SITE_NAMES[@]}"
do
  mkdir -p $(pwd)/${SITE_NAMES}
  cp -r $(pwd)/wordpress/* $(pwd)/${SITE_NAMES} || true
  # sudo chown -R root:root $(pwd)/${SITE_NAMES} || true
  sudo chmod 777 root:root $(pwd)/${SITE_NAMES} || true
  sudo chmod 777 root:root $(pwd)/${SITE_NAMES}/wp-admin || true
  sudo chmod 777 root:root $(pwd)/${SITE_NAMES}/wp-includes || true
  sudo chmod 777 root:root $(pwd)/${SITE_NAMES}/wp-content || true
  sudo chmod 777 root:root $(pwd)/${SITE_NAMES}/wp-content/themes || true
  sudo chmod 777 root:root $(pwd)/${SITE_NAMES}/wp-content/plugins || true
  sudo chmod 777 root:root $(pwd)/${SITE_NAMES}/wp-content/uploads || true
  sudo chmod 644 root:root $(pwd)/${SITE_NAMES}/.htaccess || true
  sudo chmod 644 root:root $(pwd)/${SITE_NAMES}/index.php || true
  # chmod -R 644 $(pwd)/${SITE_NAMES}/wp-config.php || true
  SITE_NAME=${SITE_NAMES[$i]}
  docker volume create ${SITE_NAME}_wordpress || true
  docker volume create ${SITE_NAME}_mariadb || true
done

source $(pwd)/site
source $(pwd)/htpasswd
source $(pwd)/compose
source $(pwd)/proxy

echo "...compose up"
docker compose up -d --build --force-recreate
